### ISSUE TITLE
Compiling with VS 2015 gives an error.

### ISSUE THREAD

**Issue by klshrinidhi** [Biomechanical-ToolKit/BTKCore#10]
When trying to compile the sources with VS 2015, I am getting the following error:
https://ci.appveyor.com/project/opensim-org/opensim-core/build/1949

The sources compile successfully with gcc and clang. 

Is there any configuration flag I am missing for Windows build ?

**Comment by Alzathar** [comment]
I would say this is an issue with the version of Eigen used in the master branch of BTKCore. Can you try to update the version of Eigen in your own repository to see if it fixes your problem? If it is the case you could then pull a request.

**Comment by Alzathar** [comment]
Fixed by the Pull Request #11.
